name: Publish and Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.2.5

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build

      - name: Zip the built artifacts
        run: zip -r -q dist.zip dist

      - name: Pwd
        run: pwd

      - name: Ls
        run: ls -l

      # https://github.com/marketplace/actions/upload-asset
      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: dist.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}


      #- name: Deploy
        #  if: success()
        #uses: peaceiris/actions-gh-pages@v3
          #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: dist/angular-github-actions
        #enable_jekyll: true